#Phase 1 batch processing
version: "3.8"

services:
  spark-batch:
    build:
      context: ./batch
    volumes:
      - /Users/alex/mydata/BGL_extracted/BGL.log:/data/BGL.log
      - ./output:/output
      - ./batch:/app
    environment:
      - DATA_PATH=/data/BGL.log
      - OUTPUT_PATH=/output