#Phase 1 batch processing
version: "3.8"

services:
  spark-batch:
    build:
      context: ./batch
    volumes:
      - /Users/alex/mydata/BGL_extracted/BGL.log:/data/BGL.log
      - ./output:/output
      - ./batch:/app
    environment:
      - DATA_PATH=/data/BGL.log
      - OUTPUT_PATH=/output
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  producer:
    build:
      context: ./streaming/producer
    depends_on:
      - kafka
    volumes:
      - /Users/alex/mydata/BGL_extracted/BGL.log:/data/BGL.log
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=bgl-logs
      - DATA_PATH=/data/BGL.log
      - PYTHONUNBUFFERED=1
  consumer:
    build:
      context: ./streaming/consumer
    depends_on:
      - kafka
    volumes:
      - ./streaming/consumer:/app
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=bgl-logs
      - PYTHONUNBUFFERED=1